import type { CompareBasis, PeriodMode } from "@/data/types";
import {
  getDashboardBundle,
  getDetailedVariance,
  type Filters,
} from "@/lib/metrics";
import { formatCurrency, formatPct, periodLabel } from "@/lib/format";

export function buildNarrative(filters: Filters): {
  headline: string;
  bullets: string[];
  risks: string[];
  actions: string[];
  fullText: string;
} {
  const bundle = getDashboardBundle(filters);
  const basis = filters.basis ?? "budget";
  const basisLabel =
    basis === "budget" ? "budget" : basis === "forecast" ? "forecast" : "prior year";
  const revVar = bundle.pnl.revenue.actual - bundle.pnl.revenue[basis];
  const ebitdaVar = bundle.pnl.ebitda.actual - bundle.pnl.ebitda[basis];
  const top = bundle.detailedVariance.slice(0, 3);
  const worst = [...bundle.detailedVariance].sort((a, b) => a.variance - b.variance)[0];
  const best = [...bundle.detailedVariance].sort((a, b) => b.variance - a.variance)[0];

  const headline =
    Math.abs(revVar) < bundle.pnl.revenue[basis] * 0.01
      ? `Revenue tracking near ${basisLabel} for ${periodLabel(filters.period)} (${filters.mode}).`
      : revVar > 0
        ? `Revenue ahead of ${basisLabel} by ${formatCurrency(revVar, { compact: true })} — led by ${best?.label ?? "mix"}.`
        : `Revenue behind ${basisLabel} by ${formatCurrency(Math.abs(revVar), { compact: true })} — watch ${worst?.label ?? "underperformers"}.`;

  const bullets = [
    `Actual revenue ${formatCurrency(bundle.pnl.revenue.actual, { compact: true })} vs ${basisLabel} ${formatCurrency(bundle.pnl.revenue[basis], { compact: true })} (${formatPct((revVar / (bundle.pnl.revenue[basis] || 1)) * 100)}).`,
    `EBITDA ${formatCurrency(bundle.pnl.ebitda.actual, { compact: true })} (${bundle.pnl.ebitdaMarginPct.toFixed(1)}% margin); variance to ${basisLabel} ${formatCurrency(ebitdaVar, { compact: true, signed: true })}.`,
    `Field utilization ${bundle.ops.utilizationPct}% on ${bundle.ops.billableDays}/${bundle.ops.availableDays} billable days; backlog ${formatCurrency(bundle.ops.backlogRevenue, { compact: true })}.`,
    ...top.map((t) => {
      const tone = t.variance >= 0 ? "favorable" : "unfavorable";
      const driver = t.drivers[0];
      return `${t.label}: ${formatCurrency(t.variance, { compact: true, signed: true })} (${tone}). Primary driver — ${driver?.label ?? "mix"}: ${driver?.note ?? ""}`;
    }),
  ];

  const risks: string[] = [];
  if (bundle.ops.utilizationPct < 70) {
    risks.push(
      `Utilization at ${bundle.ops.utilizationPct}% signals idle crew/equipment risk to near-term margin and cash conversion.`,
    );
  }
  if (worst && worst.variance < 0) {
    risks.push(
      `${worst.label} is the largest drag (${formatCurrency(worst.variance, { compact: true })}). ${worst.drivers.find((d) => d.code === "volume" || d.code === "cost")?.note ?? ""}`,
    );
  }
  if (bundle.pnl.grossMarginPct < 35) {
    risks.push(
      `Gross margin compressed to ${bundle.pnl.grossMarginPct.toFixed(1)}% — review mobilization costs and day-rate discipline.`,
    );
  }
  if (risks.length === 0) {
    risks.push("No acute red flags in the current slice; monitor Atlantic softness and winter seasonality into H2.");
  }

  const actions = [
    "Re-forecast Prairies Drilling if weather/mobilization slippage persists beyond one period.",
    "Lock Pacific CPT surge capacity and confirm corridor change orders before month close.",
    "Pair utilization heatmap with cash forecast — idle hours are a working-capital tell.",
    "Publish this variance narrative into the monthly pack and review with region leads.",
  ];

  const fullText = [
    `# FieldOps FP&A Brief — ${periodLabel(filters.period)} (${filters.mode})`,
    "",
    headline,
    "",
    "## Key points",
    ...bullets.map((b) => `- ${b}`),
    "",
    "## Risks",
    ...risks.map((r) => `- ${r}`),
    "",
    "## Recommended actions",
    ...actions.map((a) => `- ${a}`),
    "",
    "_Generated by FieldOps FP&A Analyst._",
  ].join("\n");

  return { headline, bullets, risks, actions, fullText };
}

export function answerQuestion(
  question: string,
  filters: Filters,
): string {
  const q = question.toLowerCase();
  const bundle = getDashboardBundle(filters);
  const basis = filters.basis ?? "budget";
  const detailed = getDetailedVariance(filters);

  if (q.includes("utilization") || q.includes("crew") || q.includes("idle")) {
    return `Utilization is ${bundle.ops.utilizationPct}% (${bundle.ops.billableDays} of ${bundle.ops.availableDays} days). Equipment idle hours total ${bundle.ops.equipmentIdleHours.toLocaleString("en-CA")}. In FP&A terms, every 5pt utilization swing typically moves revenue via volume before rate/mix — check the Variance Lab drivers for confirmation.`;
  }
  if (q.includes("pacific") || q.includes("cpt") || q.includes("lng")) {
    const line = detailed.find((d) => d.label.includes("Pacific") && d.label.includes("CPT"));
    if (line) {
      return `Pacific · CPT variance vs ${basis}: ${formatCurrency(line.variance, { signed: true, compact: true })} (${formatPct(line.variancePct)}). ${line.drivers.map((d) => d.note).join(" ")} Performance was lifted by a large corridor program in May 2026.`;
    }
  }
  if (q.includes("prairies") || q.includes("drilling") || q.includes("weather")) {
    const line = detailed.find((d) => d.label.includes("Prairies") && d.label.includes("Drilling"));
    if (line) {
      return `Prairies · Drilling: ${formatCurrency(line.variance, { signed: true, compact: true })} vs ${basis}. ${line.drivers[0]?.note ?? ""} Review volume and remobilization costs before locking the next forecast.`;
    }
  }
  if (q.includes("ebitda") || q.includes("margin") || q.includes("profit")) {
    return `EBITDA is ${formatCurrency(bundle.pnl.ebitda.actual, { compact: true })} (${bundle.pnl.ebitdaMarginPct.toFixed(1)}% of revenue). Gross margin ${bundle.pnl.grossMarginPct.toFixed(1)}%. Bridge vs ${basis}: revenue var ${formatCurrency(bundle.pnl.revenue.actual - bundle.pnl.revenue[basis], { signed: true, compact: true })}, COGS pressure ${formatCurrency(bundle.pnl.cogs.actual - bundle.pnl.cogs[basis], { signed: true, compact: true })}.`;
  }
  if (q.includes("cash") || q.includes("working capital") || q.includes("backlog")) {
    return `Backlog sits at ${formatCurrency(bundle.ops.backlogRevenue, { compact: true })}. Idle equipment hours (${bundle.ops.equipmentIdleHours.toLocaleString("en-CA")}) are a leading indicator for cash timing — revenue recognition lags remobilization. Pair this with AR aging in a live ERP (Dynamics/NetSuite) for a full working-capital view.`;
  }
  if (q.includes("budget") || q.includes("forecast") || q.includes("variance") || q.includes("why")) {
    const top = detailed.slice(0, 3);
    return `Top absolute revenue variances vs ${basis}: ${top.map((t) => `${t.label} ${formatCurrency(t.variance, { signed: true, compact: true })}`).join("; ")}. Open Variance Lab to switch basis and expand a row for volume / rate / mix / cost drivers.`;
  }

  const revVar = bundle.pnl.revenue.actual - bundle.pnl.revenue[basis];
  return `For ${periodLabel(filters.period)} (${filters.mode}), revenue is ${formatCurrency(bundle.pnl.revenue.actual, { compact: true })} (${formatCurrency(revVar, { signed: true, compact: true })} vs ${basis}). Ask about utilization, Pacific CPT, Prairies Drilling, EBITDA, or backlog for a sharper answer — or generate the Monthly Pack for a full brief.`;
}

export function defaultFilters(
  overrides: Partial<{
    period: string;
    mode: PeriodMode;
    basis: CompareBasis;
    region: Filters["region"];
    serviceLine: Filters["serviceLine"];
  }> = {},
): Filters {
  return {
    period: overrides.period ?? "2026-06",
    mode: overrides.mode ?? "YTD",
    basis: overrides.basis ?? "budget",
    region: overrides.region ?? "All",
    serviceLine: overrides.serviceLine ?? "All",
  };
}
